version: "3.9"

services:
  l2vibe_service:
    container_name: l2vibe_service
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - PUBLIC_JWT_KEY=${PUBLIC_JWT_KEY}
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - public_network
      - private_network
    restart: always

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports: 
      - ${DB_PORT}:3306
    networks:
      - private_network

networks:
  public_network:
    driver: bridge

  private_network:
    driver: bridge
    internal: true